# Data analysis overview

In [1]:
import numpy as np
arr = np.random.randn(4,4) #for integers, use #np.random.randint()
np.where(arr>0,2,-2)

array([[ 2,  2, -2,  2],
       [-2, -2,  2, -2],
       [-2,  2, -2, -2],
       [ 2,  2, -2,  2]])

In [2]:
np.where(arr>0,2,arr)

array([[ 2.        ,  2.        , -0.84490256,  2.        ],
       [-0.04915673, -0.90930763,  2.        , -0.57954525],
       [-1.54312925,  2.        , -1.80409965, -0.78139032],
       [ 2.        ,  2.        , -0.93168796,  2.        ]])

In [3]:
arr2 = np.array([0,1,2,3,4,5,6,7])
arr2.cumsum() #cumsum return an array of the same size

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [4]:
arr3 = np.array([[0,1,2], [3,4,5], [6,7,8]])
arr3.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [5]:
#arr.sort(), arr.unique() are also useful functions to take note of

## Working with pandas

In [8]:
import pandas as pd
from pandas import Series, DataFrame
obj = pd.Series([4, 7, -5, 3])
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
print(obj2)
print(np.exp(obj2))

d    4
b    7
a   -5
c    3
dtype: int64
d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64


In [10]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
print(obj3)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64


In [11]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [12]:
pd.DataFrame(data, columns=['year', 'state', 'pop']) #reorder 

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [ ]:
# Indexing options with DataFrame
###### df[val] Select single column or sequence of columns from the DataFrame; special case
###### df.loc[val] Selects single row or subset of rows from the DataFrame by label
###### df.loc[:, val] Selects single column or subset of columns by label
###### df.loc[val1, val2] Select both rows and columns by label
###### df.iloc[where] Selects single row or subset of rows from the DataFrame by integer position
###### df.iloc[:, where] Selects single column or subset of columns by integer position
###### df.iloc[where_i, where_j] Select both rows and columns by integer position
###### df.at[label_i, label_j] Select a single scalar value by row and column label
###### df.iat[i, j] Select a single scalar value by row and column position (integers)
###### reindex method Select either rows or columns by labels
###### get_value, set_value methods Select single value by row and column label
##### obj.sort_index() for sorting